version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
